# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Max In Business
email: maxfischer767@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Follow my entrepreneurial journey.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: maxfischer767
github_username:  maxinbusiness

# Build settings
markdown: kramdown
port: 8888

permalink: none
markdown_ext: "markdown,mkdown,mkdn,mkd,md,html"